version: '3.9'

services:
  app:
    build: .
    container_name: school-book-storage-frontend
    hostname: school-book-storage-frontend
    pull_policy: always
    restart: always
    ports:
      - ${APP_PORT}:80
    environment:
      API_BASE_URL: ${API_BASE_URL}
