version: '3.9'

services:
  app:
    image: kammeph/school-book-storage-frontend:${APP_VERSION}
    container_name: school-book-storage-frontend
    hostname: school-book-storage-frontend
    pull_policy: always
    restart: always
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - ${APP_PORT}:80
