name: deploy-dev

on:
  push:
    branches: ['dev']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: build
        run: pnpm run build

      - name: test
        run: pnpm run test

  docker-push:
    name: build Docker image and push to Docker Hub
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64, linux/arm64 #, linux/386, linux/arm/v6, linux/arm/v7, linux/ppc64le, linux/s390x
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/school-book-storage-frontend:dev

  redeploy:
    name: redeploy on portainer
    needs: docker-push
    runs-on: ubuntu-latest
    steps:
      - name: call portainer webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.PORTAINER_DEV_WEBHOOK_URL }}
